"""Run generated-tool tests only through the bounded NemoClaw workspace."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
from pathlib import Path, PurePosixPath
from typing import Protocol
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field

from automation_foundry.authoring.generation import HermesClient
from automation_foundry.authoring.workspace import WorkspaceBridge

_HARNESS = r'''"""NemoClaw-only generated tool test harness."""
import hashlib
import importlib.util
import json
import resource
import signal
import sys
import traceback
from pathlib import Path

request = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
resource.setrlimit(resource.RLIMIT_CPU, (request["cpu_seconds"], request["cpu_seconds"]))
memory = request["memory_mb"] * 1024 * 1024
resource.setrlimit(resource.RLIMIT_AS, (memory, memory))
resource.setrlimit(resource.RLIMIT_FSIZE, (request["max_output_bytes"], request["max_output_bytes"]))
signal.alarm(request["wall_seconds"])
tools_path = Path(request["tools_path"])
tests_path = Path(request["tests_path"])
result_path = Path(request["result_path"])
code_hash = hashlib.sha256(tools_path.read_bytes()).hexdigest()
tests_hash = hashlib.sha256(tests_path.read_bytes()).hexdigest()
failures = []
tests_run = 0
try:
    spec = importlib.util.spec_from_file_location("generated_tools", tools_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    namespace = {name: getattr(module, name) for name in dir(module) if not name.startswith("_")}
    exec(compile(tests_path.read_text(encoding="utf-8"), str(tests_path), "exec"), namespace)
    for name, value in sorted(namespace.items()):
        if name.startswith("test_") and callable(value):
            tests_run += 1
            try:
                value()
            except Exception:
                failures.append(f"{name}: {traceback.format_exc(limit=2)[-2000:]}")
except Exception:
    failures.append(traceback.format_exc(limit=3)[-4000:])
result = {
    "passed": not failures and tests_run > 0,
    "code_sha256": code_hash,
    "tests_sha256": tests_hash,
    "tests_run": tests_run,
    "failures": failures[:100],
}
result_path.write_text(json.dumps(result), encoding="utf-8")
'''


class ToolTestJob(BaseModel):
    """Paths and resource policy for a sandbox-only generated-tool test job."""

    id: UUID
    host_root: Path
    sandbox_root: PurePosixPath
    request_path: PurePosixPath
    result_path: PurePosixPath


class ToolTestResult(BaseModel):
    """Bounded test result bound to exact generated bytes."""

    model_config = ConfigDict(extra="forbid")

    passed: bool
    code_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    tests_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    tests_run: int = Field(ge=0, le=10_000)
    failures: list[str] = Field(default_factory=list, max_length=100)


class ToolTestExecutor(Protocol):
    """NemoClaw adapter that executes a staged request inside the sandbox."""

    async def execute(self, job: ToolTestJob) -> str:
        """Return the bounded JSON test result without executing code on the host."""
        ...


class HermesToolTestExecutor:
    """Ask Hermes to launch the fixed test harness inside its NemoClaw sandbox."""

    def __init__(self, client: HermesClient, workspace: WorkspaceBridge):
        """Initialize the sandbox executor.

        Args:
            client: Hermes agent API client.
            workspace: Authenticated sandbox workspace transport.
        """
        self.client = client
        self.workspace = workspace

    async def execute(self, job: ToolTestJob) -> str:
        """Run only the staged harness command and retrieve its bounded result file."""
        await self.client.complete(
            system_prompt=(
                "You are operating inside the configured NemoClaw sandbox. Run exactly the fixed generated-tool "
                "test harness requested by the user. Do not inspect host paths, change policy, or run another command."
            ),
            user_prompt=(
                f"Run: python {job.sandbox_root}/input/run_tool_tests.py {job.request_path}\n"
                f"Confirm that the harness writes {job.result_path}, then stop."
            ),
        )
        result_path = job.host_root / "output" / "result.json"
        self.workspace.download_tool_test_result(job.result_path, result_path)
        if not result_path.is_file():
            raise RuntimeError("NemoClaw tool test result is missing")
        if result_path.stat().st_size > 1_000_000:
            raise ValueError("NemoClaw tool test result exceeds configured output limit")
        return result_path.read_text(encoding="utf-8")


class SandboxToolTestRunner:
    """Stage generated code and accept only hash-bound sandbox results."""

    def __init__(self, workspace: WorkspaceBridge, executor: ToolTestExecutor):
        self.workspace = workspace
        self.executor = executor

    async def run(self, version_root: Path) -> ToolTestResult:
        """Run tool tests through NemoClaw and persist a verified receipt."""
        tools_path = version_root / "tools.py"
        tests_path = version_root / "test_tools.py"
        manifest_path = version_root / "tool_manifest.json"
        for path in (tools_path, tests_path, manifest_path):
            if not path.is_file():
                raise FileNotFoundError(f"Generated tool artifact is missing: {path.name}")
        self.workspace._assert_ready()
        job_id = uuid4()
        relative_root = Path("automation-foundry") / "tool-tests" / str(job_id)
        host_root = self.workspace.config.host_mount / relative_root
        input_root = host_root / "input"
        output_root = host_root / "output"
        input_root.mkdir(parents=True, exist_ok=False)
        output_root.mkdir()
        for path in (tools_path, tests_path, manifest_path):
            shutil.copy2(path, input_root / path.name)
        (input_root / "run_tool_tests.py").write_text(_HARNESS, encoding="utf-8")

        code_hash = _sha256(tools_path.read_bytes())
        tests_hash = _sha256(tests_path.read_bytes())
        sandbox_root = self.workspace.config.sandbox_root / PurePosixPath(relative_root.as_posix())
        request = {
            "schema_version": "1.0",
            "runner": "python-isolated",
            "network": "deny",
            "read_only_inputs": True,
            "cpu_seconds": 5,
            "wall_seconds": 10,
            "memory_mb": 512,
            "max_output_bytes": 1_000_000,
            "tools_path": str(sandbox_root / "input/tools.py"),
            "tests_path": str(sandbox_root / "input/test_tools.py"),
            "manifest_path": str(sandbox_root / "input/tool_manifest.json"),
            "code_sha256": code_hash,
            "tests_sha256": tests_hash,
            "result_path": str(sandbox_root / "output/result.json"),
        }
        (host_root / "request.json").write_text(
            f"{json.dumps(request, indent=2, sort_keys=True)}\n", encoding="utf-8"
        )
        job = ToolTestJob(
            id=job_id,
            host_root=host_root,
            sandbox_root=sandbox_root,
            request_path=sandbox_root / "request.json",
            result_path=sandbox_root / "output/result.json",
        )
        self.workspace.publish_tool_test(job.host_root, job.sandbox_root)
        raw_result = await self.executor.execute(job)
        if len(raw_result.encode("utf-8")) > 1_000_000:
            raise ValueError("Sandbox tool test result exceeds configured output limit")
        result = ToolTestResult.model_validate_json(raw_result)
        if result.code_sha256 != code_hash or result.tests_sha256 != tests_hash:
            raise ValueError("Sandbox tool test result does not match generated bytes")
        temporary = version_root / ".tool_test_result.json.pending"
        temporary.write_text(f"{result.model_dump_json(indent=2)}\n", encoding="utf-8")
        os.replace(temporary, version_root / "tool_test_result.json")
        return result


def _sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()
