"""Public contracts shared by authoring and execution lanes."""

from automation_foundry.contracts.models import (
    ApprovalDecision,
    ApprovalRecord,
    ApprovedBundle,
    ArtifactReference,
    AutomationManifest,
    AutomationStatus,
    AutomationVersion,
    ConflictSeverity,
    EvidenceReference,
    EvidenceSourceType,
    FieldChange,
    GeneratedTool,
    InputDefinition,
    InvocationSource,
    ProcedureCheck,
    ProcedureStep,
    ReviewConflict,
    RunEvent,
    RunPreview,
    RunRequest,
    RunResult,
    RunState,
    SourceMetadata,
    StagedChange,
)
from automation_foundry.contracts.transitions import ALLOWED_RUN_TRANSITIONS, require_run_transition

__all__ = [
    "ALLOWED_RUN_TRANSITIONS",
    "ApprovalDecision",
    "ApprovalRecord",
    "ApprovedBundle",
    "ArtifactReference",
    "AutomationManifest",
    "AutomationStatus",
    "AutomationVersion",
    "ConflictSeverity",
    "EvidenceReference",
    "EvidenceSourceType",
    "FieldChange",
    "GeneratedTool",
    "InputDefinition",
    "InvocationSource",
    "ProcedureCheck",
    "ProcedureStep",
    "ReviewConflict",
    "RunEvent",
    "RunPreview",
    "RunRequest",
    "RunResult",
    "RunState",
    "SourceMetadata",
    "StagedChange",
    "require_run_transition",
]
